const $=id=>document.getElementById(id);\nlet deferredInstall=null;\nwindow.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;const b=$("install-finance");if(b)b.hidden=false});\n$("install-finance")?.addEventListener("click",async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$("install-finance").hidden=true});const money=n=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:2}).format(Number(n)||0);
function payment(p,apr,months){const r=(Number(apr)||0)/100/12,n=Number(months)||1,a=Number(p)||0;return r? a*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):a/n}
$("f-calc").onclick=()=>{const income=+$("f-income").value,essential=+$("f-essential").value,debt=+$("f-debt").value,amount=+$("f-amount").value,term=+$("f-term").value,apr=+$("f-apr").value;const spare=income-essential-debt,p=payment(amount,apr,term),safe=Math.max(0,spare*0.8);$("f-result").innerHTML='<strong>Estimated payment: '+money(p)+'/month</strong><br>After your listed essentials and existing credit: <strong>'+money(spare)+'</strong> remains. A cautious planning ceiling of 80% of that is <strong>'+money(safe)+'</strong>.<br><span class="finance-muted">If the payment is above what you can comfortably afford, stop there. A lender accepting an application does not make it affordable.</span>'};
$("c-calc").onclick=()=>{const a=+$("c-amount").value,m=+$("c-monthly").value,n=+$("c-payments").value,d=+$("c-deposit").value,f=+$("c-fees").value;const total=m*n+d+f,interest=total-a; $("c-result").innerHTML='<strong>Total cash cost: '+money(total)+'</strong><br>Approximate cost above the financed amount: <strong>'+money(interest)+'</strong>.<br><span class="finance-muted">Also check APR, balloon/final payment, optional products, early-settlement terms and whether the quoted monthly payment depends on a deposit.</span>'};
const routes={personal:["Personal loan","Compare fixed APR, total repayment, fees, term and early settlement. Prefer an eligibility checker before a full application."],car:["Car finance","Ask whether it is HP or PCP, record the deposit, monthly payment, term, mileage limits, balloon/final payment, fees and ownership position."],card:["Credit card","Compare APR, promotional period, transfer fees, credit limit, minimum payments and what happens when a promotional rate ends."],consolidation:["Debt consolidation","Do not compare only the monthly payment. Compare total cost, term, fees and whether you are securing debt against an asset. A lower payment can still mean a higher total cost."]};
document.querySelectorAll("[data-route]").forEach(b=>b.onclick=()=>{const r=routes[b.dataset.route];$("route-result").innerHTML='<strong>'+r[0]+'</strong><br>'+r[1]});
function packText(){const docs=[...document.querySelectorAll("[data-doc]:checked")].map(x=>"✓ "+x.dataset.doc).join("\n")||"No documents ticked yet";return "PLEADING SANITY · FINANCE APPLICATION PACK\n\nDOCUMENTS\n"+docs+"\n\nFACTUAL COVER NOTE\n"+($("letter").value.trim()||"Add only truthful facts relevant to the application.")};
$("make-letter").onclick=()=>{$("pack-result").textContent=packText()+"\n\nThis note is a preparation aid. The applicant should check every statement before sending it."};
$("copy-pack").onclick=async()=>{await navigator.clipboard.writeText(packText());$("pack-result").textContent="Application pack copied. Check it before sending."};
$("ask-adviser").onclick=async()=>{const q=$("a-question").value.trim();if(!q)return;$("a-result").textContent="The family is checking the question…";try{const r=await fetch("/api/finance-adviser",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({question:q,quote:$("a-quote")?.value.trim()||""})});const d=await r.json();if(!r.ok)throw Error(d.error||"No answer");$("a-result").textContent=d.reply}catch(e){$("a-result").textContent=e.message||"Try again in a moment."}};

document.querySelectorAll(".finance-chip").forEach(b=>b.addEventListener("click",()=>{$("a-question").value=b.dataset.question;$("a-question").focus()}));
$("save-brief")?.addEventListener("click",()=>{const brief={question:$("a-question").value.trim(),quote:$("a-quote").value.trim(),savedAt:new Date().toISOString()};localStorage.setItem("ps-sane-finance-brief",JSON.stringify(brief));$("a-result").textContent="Your finance brief was saved on this device only."});
const saved=localStorage.getItem("ps-sane-finance-brief");if(saved){try{const b=JSON.parse(saved);if(b.question)$("a-question").value=b.question;if(b.quote)$("a-quote").value=b.quote}catch{}}
if("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js",{scope:"/"}).catch(()=>{});

$("j-check")?.addEventListener("click",()=>{
 const credit=$("j-credit").value,income=$("j-income").value,afford=$("j-afford").value,outcome=$("j-outcome").value;
 const blockers=[],steps=[];
 if(outcome==="declined"){blockers.push("The lender has declined the application, but the private underwriting reason is not visible to this tool.");steps.push("Ask the lender for the specific adverse reason or eligibility criterion, and whether a manual review or appeal is available.");}
 if(outcome==="criteria"){blockers.push("An eligibility criterion was not met. The exact criterion must be confirmed by the provider.");steps.push("Do not immediately apply elsewhere. Record the failed criterion, check whether it is temporary, and use an eligibility checker where available.");}
 if(outcome==="referred"){blockers.push("The application needs manual review. This is not the same as a final refusal.");steps.push("Wait for the provider's decision and provide only the documents they genuinely request.");}
 if(credit==="late"){blockers.push("Recent missed or late payments can narrow lender choice.");steps.push("Check all three credit reports for errors and avoid unnecessary hard applications.");}
 if(credit==="default"){blockers.push("Defaults can materially affect eligibility, especially when recent or unpaid.");steps.push("Record dates, balances and settlement status. Look for providers whose published criteria actually fit.");}
 if(credit==="ccj"){blockers.push("A CCJ can restrict mainstream options depending on date, amount and status.");steps.push("Record the CCJ date, amount and whether it is satisfied. Use only providers whose criteria explicitly cover your situation.");}
 if(credit==="iva"){blockers.push("An IVA or other debt solution can make new borrowing unsuitable or restricted.");steps.push("Speak to the organisation administering the debt solution before seeking new credit.");}
 if(credit==="thin"){blockers.push("Limited credit history can make automated decisions harder.");steps.push("Use eligibility tools where available and avoid applying to multiple lenders just to test acceptance.");}
 if(income==="variable"||income==="self"||income==="newjob"){blockers.push("Income stability or evidence requirements may affect eligibility.");steps.push("Prepare accurate income evidence and check the provider's exact employment criteria.");}
 if(income==="benefits"){blockers.push("Whether benefits count depends on the provider and the type of benefit.");steps.push("Check the provider's current criteria before a full application and never guess at annual income.");}
 if(afford==="tight"){blockers.push("The proposed payment appears tight against the figures entered.");steps.push("Reduce the amount, increase the deposit, extend the term only after checking total cost, or consider not borrowing.");}
 if(afford==="unknown"){steps.push("Run the affordability calculator before applying.");}
 if(!blockers.length) blockers.push("No common blocker was selected. That is not an approval prediction.");
 steps.push("Compare APR, total repayment, fees, deposit, final/balloon payment and early-settlement terms.");
 steps.push("Check the provider or broker on the FCA Register before paying a fee or sharing sensitive documents.");
 $("j-result").innerHTML="<strong>Likely blockers</strong><br>• "+blockers.join("<br>• ")+"<br><br><strong>Next steps</strong><br>• "+steps.join("<br>• ")+"<br><br><span class='finance-muted'>Important: only the lender can give the definitive reason for a decline. We will never manufacture one.</span>";
});
